package com.diegoschivo.samples.apache.cxf.sum;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-16T08:40:31.908+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://sum.cxf.apache.samples.diegoschivo.com/", name = "Sum")
@XmlSeeAlso({ObjectFactory.class})
public interface Sum {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://sum.cxf.apache.samples.diegoschivo.com/", className = "com.diegoschivo.samples.apache.cxf.sum.Sum_Type")
    @WebMethod
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://sum.cxf.apache.samples.diegoschivo.com/", className = "com.diegoschivo.samples.apache.cxf.sum.SumResponse")
    public int sum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
