/**
 *    Copyright 2013 Diego Schivo
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package com.diegoschivo.samples.apache.cxf.sum;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-16T08:40:31.908+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://sum.cxf.apache.samples.diegoschivo.com/", name = "Sum")
@XmlSeeAlso({ObjectFactory.class})
public interface Sum {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://sum.cxf.apache.samples.diegoschivo.com/", className = "com.diegoschivo.samples.apache.cxf.sum.Sum_Type")
    @WebMethod
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://sum.cxf.apache.samples.diegoschivo.com/", className = "com.diegoschivo.samples.apache.cxf.sum.SumResponse")
    public int sum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
