
package com.diegoschivo.samples.apache.cxf.sum;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-16T08:40:31.916+02:00
 * Generated source version: 2.7.5
 * 
 */
 
public class Sum_SumPort_Server{

    protected Sum_SumPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SumImpl();
        String address = "http://localhost:8080/apache-cxf-sample1/services/sum";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Sum_SumPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
