
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.diegoschivo.samples.apache.cxf.sum;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-16T08:40:31.852+02:00
 * Generated source version: 2.7.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "SumService",
                      portName = "SumPort",
                      targetNamespace = "http://sum.cxf.apache.samples.diegoschivo.com/",
                      wsdlLocation = "file:/home/diego/git/samples/apache-cxf-sample2/src/main/resources/sum.wsdl",
                      endpointInterface = "com.diegoschivo.samples.apache.cxf.sum.Sum")
                      
public class SumImpl implements Sum {

    private static final Logger LOG = Logger.getLogger(SumImpl.class.getName());

    /* (non-Javadoc)
     * @see com.diegoschivo.samples.apache.cxf.sum.Sum#sum(int  arg0 ,)int  arg1 )*
     */
    public int sum(int arg0,int arg1) { 
        LOG.info("Executing operation sum");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            // int _return = 0;
            int _return = arg0 + arg1;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
