package com.diegoschivo.samples.apache.cxf.sum;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-16T08:40:31.921+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "SumService", 
                  wsdlLocation = "file:/home/diego/git/samples/apache-cxf-sample2/src/main/resources/sum.wsdl",
                  targetNamespace = "http://sum.cxf.apache.samples.diegoschivo.com/") 
public class SumService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sum.cxf.apache.samples.diegoschivo.com/", "SumService");
    public final static QName SumPort = new QName("http://sum.cxf.apache.samples.diegoschivo.com/", "SumPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/diego/git/samples/apache-cxf-sample2/src/main/resources/sum.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SumService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/diego/git/samples/apache-cxf-sample2/src/main/resources/sum.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SumService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SumService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SumService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Sum
     */
    @WebEndpoint(name = "SumPort")
    public Sum getSumPort() {
        return super.getPort(SumPort, Sum.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Sum
     */
    @WebEndpoint(name = "SumPort")
    public Sum getSumPort(WebServiceFeature... features) {
        return super.getPort(SumPort, Sum.class, features);
    }

}
